# Generated by Django 2.0.3 on 2018-03-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScilabCloudComment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField()),
                ('comment', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('books', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('example', models.IntegerField()),
                ('reply', models.TextField()),
                ('reply_status', models.IntegerField(default='0')),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scilab_cloud_comment',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionCategoryList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('maincategory', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'list_of_category',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionChapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cloud_chapter_err_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'textbook_companion_chapter',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionDependencyFiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('preference_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=500)),
                ('filemime', models.CharField(max_length=255)),
                ('filesize', models.IntegerField()),
                ('caption', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'textbook_companion_dependency_files',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionExample',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('approver_uid', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('caption', models.CharField(max_length=255)),
                ('approval_date', models.IntegerField()),
                ('approval_status', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('cloud_err_status', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.TextbookCompanionChapter')),
            ],
            options={
                'db_table': 'textbook_companion_example',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionExampleDependency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('example_id', models.IntegerField()),
                ('dependency_id', models.IntegerField()),
                ('approval_status', models.IntegerField()),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'textbook_companion_example_dependency',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionExampleFiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=500)),
                ('filemime', models.CharField(max_length=255)),
                ('filesize', models.IntegerField()),
                ('filetype', models.CharField(max_length=1)),
                ('caption', models.CharField(max_length=100)),
                ('timestamp', models.IntegerField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.TextbookCompanionExample')),
            ],
            options={
                'db_table': 'textbook_companion_example_files',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionExampleViews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField(default=0)),
                ('example_id', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'textbook_companion_example_views',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionPreference',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pref_number', models.IntegerField()),
                ('book', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=25)),
                ('publisher', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('category', models.IntegerField()),
                ('approval_status', models.IntegerField()),
                ('cloud_pref_err_status', models.IntegerField()),
            ],
            options={
                'db_table': 'textbook_companion_preference',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionPreferenceHits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pref_id', models.IntegerField(default=0)),
                ('hitcount', models.IntegerField(default=0)),
                ('last_search', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'textbook_companion_preference_hits',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionProposal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('uid', models.IntegerField()),
                ('approver_uid', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('how_project', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('reviewer', models.CharField(max_length=100)),
                ('completion_date', models.IntegerField()),
                ('creation_date', models.IntegerField()),
                ('approval_date', models.IntegerField()),
                ('proposal_status', models.IntegerField()),
                ('message', models.TextField()),
                ('scilab_version', models.CharField(max_length=20)),
                ('operating_system', models.CharField(max_length=20)),
                ('teacher_email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'textbook_companion_proposal',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=100)),
                ('committer_name', models.CharField(max_length=100)),
                ('committer_email', models.EmailField(max_length=254)),
                ('commit_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('push_status', models.BooleanField(default=0)),
                ('example_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.TextbookCompanionExampleFiles')),
            ],
            options={
                'db_table': 'textbook_companion_revision',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionSubCategoryList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('subcategory_id', models.IntegerField()),
                ('subcategory', models.CharField(max_length=255)),
                ('maincategory_id', models.IntegerField()),
            ],
            options={
                'db_table': 'list_of_subcategory',
            },
        ),
        migrations.AddField(
            model_name='textbookcompanionpreference',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.TextbookCompanionProposal'),
        ),
        migrations.AddField(
            model_name='textbookcompanionchapter',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.TextbookCompanionPreference'),
        ),
    ]
